### ISSUE TITLE
Замечания по работе #3.1. Добавляем новые блоки

### ISSUE THREAD

**Issue by Saintiago** [Azizvohidovic/front-end#3]
Отступы не соответствуют макету

**Comment by Saintiago** [comment]
Выполнить простейший сброс стандартных стилей браузера (https://habrahabr.ru/post/45296/).

**Comment by Saintiago** [comment]
```html
<div>
        <img src="images/background.jpg" alt="background" class="background">
    </div>
```
Фон сделать через css (свойство background).

**Comment by Saintiago** [comment]
```css
.photo {
    ...
    position: absolute;
    top: 275px;
    left: 478px;
}
```
Для позиционирования блоков не используем свойство ```position```
